// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace GithubDashboard
{
	public partial class MilestoneView : UIView
	{
		public MilestoneView (IntPtr handle) : base (handle)
		{
		}
	}
}
